import React, { useState } from "react";
import { UserCard } from "./components/UserCard";
import { ProductCard } from "./components/ProductCard";
import { TodoList } from "./components/TodoList";
import { ContactForm } from "./components/ContactForm";
import { Navigation } from "./components/Navigation";

// Notice: NO manual data-testid attributes or withTestId wrapping!
// The Babel plugin will automatically add data-testid attributes to all elements

function App() {
  const [activeTab, setActiveTab] = useState("user-cards");

  const sampleUsers = [
    {
      id: 1,
      name: "John Doe",
      email: "john@example.com",
      role: "Admin",
      avatar: "👨‍💼",
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "jane@example.com",
      role: "User",
      avatar: "👩‍💻",
    },
  ];

  const sampleProducts = [
    {
      id: 1,
      name: "Wireless Headphones",
      price: 99.99,
      description: "High-quality wireless headphones with noise cancellation",
      inStock: true,
    },
    {
      id: 2,
      name: "Smart Watch",
      price: 249.99,
      description: "Advanced smartwatch with health monitoring features",
      inStock: false,
    },
    {
      id: 3,
      name: "Laptop Stand",
      price: 49.99,
      description: "Ergonomic laptop stand for better posture",
      inStock: true,
    },
  ];

  return (
    <div className="app">
      <header>
        <h1>Auto TestId Babel Plugin Demo</h1>
        <div className="alert alert-info">
          <strong>Notice:</strong> All data-testid attributes are automatically
          generated by the Babel plugin! Open DevTools to inspect the generated
          test IDs.
        </div>
      </header>

      <Navigation activeTab={activeTab} onTabChange={setActiveTab} />

      <main>
        {activeTab === "user-cards" && (
          <section className="example-section">
            <h2>User Cards Example</h2>
            <p>
              These user cards demonstrate automatic test ID generation for
              component hierarchies.
            </p>
            <div className="user-grid">
              {sampleUsers.map((user, index) => (
                <UserCard key={user.id} user={user} />
              ))}
            </div>
          </section>
        )}

        {activeTab === "products" && (
          <section className="example-section">
            <h2>Product Catalog</h2>
            <p>Product cards with different states and interactive elements.</p>
            <div className="product-grid">
              {sampleProducts.map((product, index) => (
                <ProductCard key={product.id} product={product} />
              ))}
            </div>
          </section>
        )}

        {activeTab === "todo" && (
          <section className="example-section">
            <h2>Todo List</h2>
            <p>
              Interactive todo list demonstrating form elements and dynamic
              content.
            </p>
            <TodoList />
          </section>
        )}

        {activeTab === "contact" && (
          <section className="example-section">
            <h2>Contact Form</h2>
            <p>Form with validation and various input types.</p>
            <ContactForm />
          </section>
        )}
      </main>

      <footer>
        <p>Built with React + Vite + Babel Plugin Auto TestId</p>
        <p>
          <small>
            All test IDs are automatically generated - no manual configuration
            needed!
          </small>
        </p>
      </footer>
    </div>
  );
}

export default App;
